# config.yaml

output_dir: docs
user_agent: "VAULT/1.0 (https://github.com/sbrzt/vault)"
cache_dir: "cache"
max_workers: 20
formats:
  - mime_type: "text/turtle"
    format: "turtle"
  - mime_type: "application/rdf+xml"
    format: "xml"
  - mime_type: "application/ld+json"
    format: "json-ld"
  - mime_type: "text/n3"
    format: "n3"
  - mime_type: "application/n-triples"
    format: "nt"

ontologies:

  - label: "CiTO"
    uri: "http://purl.org/spar/cito"
    prefix: "cito"
    keywords:
      - "http://purl.org/spar/cito/"
      - "Citation Typing Ontology"
    papers:
      - "10.1016/j.websem.2012.08.001"

  - label: "FaBiO"
    uri: "http://purl.org/spar/fabio"
    prefix: "fabio"
    keywords:
      - "http://purl.org/spar/fabio/"
      - "FRBR-aligned Bibliographic Ontology"
    papers:
      - "10.1016/j.websem.2012.08.001"

  - label: "PRO"
    uri: "http://purl.org/spar/pro"
    prefix: "pro"
    keywords:
      - "http://purl.org/spar/pro/"
      - "Publishing Roles Ontology"
    papers:
      - "10.1145/2362499.2362502"


